# Generated by Django 2.2.2 on 2019-06-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190618_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posting',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterField(
            model_name='posting',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
