# Generated by Django 2.2.4 on 2019-08-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20190627_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='name',
            new_name='user',
        ),
    ]
